### ISSUE TITLE
Dock not appearing when I place mouse over it

### ISSUE THREAD

**Issue by aindriu80** [pop-os/linux#114] opened 2022-01-13 10:05 UTC
Hi,

I'm having a fair few bugs with Pop OS 21.10, one of them is the dock not appearing when I place the mouse over it.  I have Dock Visibility set to Always hide - so it only appears when the mouse is over it however it doesn't do that.  I have tried disabling the dock and trying Dash to Dock Extension but that doesn't work either.  

![2022-01-13_10-02](https://user-images.githubusercontent.com/8885837/149309000-43383cc2-daee-4dcd-8973-e0accd72485b.png)
![2022-01-13_10-02_1](https://user-images.githubusercontent.com/8885837/149309003-925716fa-9f47-4b6b-91ec-d83452cb3dac.png)
![2022-01-13_10-02_2](https://user-images.githubusercontent.com/8885837/149309006-92cf3c53-8d23-435a-8dcc-25b7a0e940cc.png)

**Comment by leviport** [comment] 2022-01-13 14:18
Duplicate of https://github.com/pop-os/cosmic-dock/issues/103

It looks like that one was resolved, but I'll reopen it for you.

**Closed by leviport** 2022-01-13 14:18 UTC

**Comment by aindriu80** [comment] 2022-01-15 12:18
Thanks, it seems a bit buggy, sometimes it works fine and other times it doesn't.  I can get it to work with a mixture of disabling it and re-enabling it and a pressing` ALT F2` and typing `r`

I had other bugs like when I clicked on Firefox in the dock it didn't appear properly, I would get a double top bar or double firefox, I would have to log out or restart Gnome.

**Comment by aindriu80** [comment] 2022-01-20 20:35
I still have this bug
